# Generated by Django 4.2 on 2024-11-20 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=25)),
                ('is_guardian', models.BooleanField(default=False)),
                ('is_view', models.BooleanField(default=False)),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女'), ('unknown', '不明')], default='unknown', max_length=10)),
                ('ent_year', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('consideration', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
